# Generated by Django 5.1 on 2024-08-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('matricula', models.IntegerField()),
                ('funcao', models.CharField(max_length=40)),
            ],
        ),
    ]
