# Generated by Django 5.1 on 2024-08-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
