# Generated by Django 5.1 on 2024-08-30 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0002_delete_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=50, verbose_name='Nome')),
                ('FUNCAO', models.CharField(max_length=50, verbose_name='Função')),
                ('DATA_CRIACAO', models.DateField(verbose_name='Data de criação')),
                ('SETOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.setor', verbose_name='Setor')),
            ],
        ),
    ]
