# Generated by Django 5.1 on 2024-08-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
