# Generated by Django 5.1 on 2024-08-30 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0003_initial'),
        ('ponto', '0002_delete_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_HORA', models.DateTimeField(verbose_name='Data e hora')),
                ('COLABORADOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador', verbose_name='Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_HORA', models.DateTimeField(verbose_name='Data e hora')),
                ('COLABORADOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador', verbose_name='Colaborador')),
            ],
        ),
    ]
